# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/model/sentiment_analysis_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/model/sentiment_analysis_rpc.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n+services/model/sentiment_analysis_rpc.proto\"\x1d\n\x0cInputMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x1e\n\rOutputMessage\x12\r\n\x05value\x18\x01 \x01(\t\"o\n\x12TwitterCredentials\x12\x14\n\x0c\x63onsumer_key\x18\x01 \x01(\t\x12\x17\n\x0f\x63onsumer_secret\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x14\n\x0ctoken_secret\x18\x04 \x01(\t\"\xea\x01\n\x13TwitterInputMessage\x12(\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x13.TwitterCredentials\x12\x11\n\tlanguages\x18\x02 \x01(\t\x12\x10\n\x08keywords\x18\x03 \x01(\t\x12\x12\n\ntime_limit\x18\x04 \x01(\x03\x12\x11\n\tmsg_limit\x18\x05 \x01(\x03\x12\x0f\n\x07product\x18\x06 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x07 \x01(\t\x12\x11\n\tfrom_date\x18\x08 \x01(\t\x12\x0f\n\x07to_date\x18\t \x01(\t\x12\x13\n\x0bmax_results\x18\n \x01(\x03\"%\n\x14TwitterOutputMessage\x12\r\n\x05value\x18\x01 \x01(\t26\n\x0bShowMessage\x12\'\n\x04show\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32T\n\x1aSentimentIntensityAnalysis\x12\x36\n\x13intensivityAnalysis\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32R\n\x1aSentimentConsensusAnalysis\x12\x34\n\x11\x63onsensusAnalysis\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32O\n\x14\x43ustomCorpusAnalysis\x12\x37\n\x14\x63ustomCorpusAnalysis\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32Y\n\x19TwitterHistoricalAnalysis\x12<\n\x12historicalAnalysis\x12\x14.TwitterInputMessage\x1a\x0e.OutputMessage\"\x00\x32Q\n\x15TwitterStreamAnalysis\x12\x38\n\x0estreamAnalysis\x12\x14.TwitterInputMessage\x1a\x0e.OutputMessage\"\x00\x32\x35\n\tTrainData\x12(\n\x05train\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x62\x06proto3')
)




_INPUTMESSAGE = _descriptor.Descriptor(
  name='InputMessage',
  full_name='InputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='InputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=76,
)


_OUTPUTMESSAGE = _descriptor.Descriptor(
  name='OutputMessage',
  full_name='OutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='OutputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=108,
)


_TWITTERCREDENTIALS = _descriptor.Descriptor(
  name='TwitterCredentials',
  full_name='TwitterCredentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_key', full_name='TwitterCredentials.consumer_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consumer_secret', full_name='TwitterCredentials.consumer_secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='access_token', full_name='TwitterCredentials.access_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token_secret', full_name='TwitterCredentials.token_secret', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=221,
)


_TWITTERINPUTMESSAGE = _descriptor.Descriptor(
  name='TwitterInputMessage',
  full_name='TwitterInputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credentials', full_name='TwitterInputMessage.credentials', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='languages', full_name='TwitterInputMessage.languages', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keywords', full_name='TwitterInputMessage.keywords', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_limit', full_name='TwitterInputMessage.time_limit', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_limit', full_name='TwitterInputMessage.msg_limit', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product', full_name='TwitterInputMessage.product', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='environment', full_name='TwitterInputMessage.environment', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_date', full_name='TwitterInputMessage.from_date', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_date', full_name='TwitterInputMessage.to_date', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='TwitterInputMessage.max_results', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=458,
)


_TWITTEROUTPUTMESSAGE = _descriptor.Descriptor(
  name='TwitterOutputMessage',
  full_name='TwitterOutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='TwitterOutputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=497,
)

_TWITTERINPUTMESSAGE.fields_by_name['credentials'].message_type = _TWITTERCREDENTIALS
DESCRIPTOR.message_types_by_name['InputMessage'] = _INPUTMESSAGE
DESCRIPTOR.message_types_by_name['OutputMessage'] = _OUTPUTMESSAGE
DESCRIPTOR.message_types_by_name['TwitterCredentials'] = _TWITTERCREDENTIALS
DESCRIPTOR.message_types_by_name['TwitterInputMessage'] = _TWITTERINPUTMESSAGE
DESCRIPTOR.message_types_by_name['TwitterOutputMessage'] = _TWITTEROUTPUTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputMessage = _reflection.GeneratedProtocolMessageType('InputMessage', (_message.Message,), dict(
  DESCRIPTOR = _INPUTMESSAGE,
  __module__ = 'services.model.sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:InputMessage)
  ))
_sym_db.RegisterMessage(InputMessage)

OutputMessage = _reflection.GeneratedProtocolMessageType('OutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTMESSAGE,
  __module__ = 'services.model.sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:OutputMessage)
  ))
_sym_db.RegisterMessage(OutputMessage)

TwitterCredentials = _reflection.GeneratedProtocolMessageType('TwitterCredentials', (_message.Message,), dict(
  DESCRIPTOR = _TWITTERCREDENTIALS,
  __module__ = 'services.model.sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:TwitterCredentials)
  ))
_sym_db.RegisterMessage(TwitterCredentials)

TwitterInputMessage = _reflection.GeneratedProtocolMessageType('TwitterInputMessage', (_message.Message,), dict(
  DESCRIPTOR = _TWITTERINPUTMESSAGE,
  __module__ = 'services.model.sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:TwitterInputMessage)
  ))
_sym_db.RegisterMessage(TwitterInputMessage)

TwitterOutputMessage = _reflection.GeneratedProtocolMessageType('TwitterOutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _TWITTEROUTPUTMESSAGE,
  __module__ = 'services.model.sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:TwitterOutputMessage)
  ))
_sym_db.RegisterMessage(TwitterOutputMessage)



_SHOWMESSAGE = _descriptor.ServiceDescriptor(
  name='ShowMessage',
  full_name='ShowMessage',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=499,
  serialized_end=553,
  methods=[
  _descriptor.MethodDescriptor(
    name='show',
    full_name='ShowMessage.show',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOWMESSAGE)

DESCRIPTOR.services_by_name['ShowMessage'] = _SHOWMESSAGE


_SENTIMENTINTENSITYANALYSIS = _descriptor.ServiceDescriptor(
  name='SentimentIntensityAnalysis',
  full_name='SentimentIntensityAnalysis',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=555,
  serialized_end=639,
  methods=[
  _descriptor.MethodDescriptor(
    name='intensivityAnalysis',
    full_name='SentimentIntensityAnalysis.intensivityAnalysis',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTIMENTINTENSITYANALYSIS)

DESCRIPTOR.services_by_name['SentimentIntensityAnalysis'] = _SENTIMENTINTENSITYANALYSIS


_SENTIMENTCONSENSUSANALYSIS = _descriptor.ServiceDescriptor(
  name='SentimentConsensusAnalysis',
  full_name='SentimentConsensusAnalysis',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=641,
  serialized_end=723,
  methods=[
  _descriptor.MethodDescriptor(
    name='consensusAnalysis',
    full_name='SentimentConsensusAnalysis.consensusAnalysis',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTIMENTCONSENSUSANALYSIS)

DESCRIPTOR.services_by_name['SentimentConsensusAnalysis'] = _SENTIMENTCONSENSUSANALYSIS


_CUSTOMCORPUSANALYSIS = _descriptor.ServiceDescriptor(
  name='CustomCorpusAnalysis',
  full_name='CustomCorpusAnalysis',
  file=DESCRIPTOR,
  index=3,
  options=None,
  serialized_start=725,
  serialized_end=804,
  methods=[
  _descriptor.MethodDescriptor(
    name='customCorpusAnalysis',
    full_name='CustomCorpusAnalysis.customCorpusAnalysis',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMCORPUSANALYSIS)

DESCRIPTOR.services_by_name['CustomCorpusAnalysis'] = _CUSTOMCORPUSANALYSIS


_TWITTERHISTORICALANALYSIS = _descriptor.ServiceDescriptor(
  name='TwitterHistoricalAnalysis',
  full_name='TwitterHistoricalAnalysis',
  file=DESCRIPTOR,
  index=4,
  options=None,
  serialized_start=806,
  serialized_end=895,
  methods=[
  _descriptor.MethodDescriptor(
    name='historicalAnalysis',
    full_name='TwitterHistoricalAnalysis.historicalAnalysis',
    index=0,
    containing_service=None,
    input_type=_TWITTERINPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWITTERHISTORICALANALYSIS)

DESCRIPTOR.services_by_name['TwitterHistoricalAnalysis'] = _TWITTERHISTORICALANALYSIS


_TWITTERSTREAMANALYSIS = _descriptor.ServiceDescriptor(
  name='TwitterStreamAnalysis',
  full_name='TwitterStreamAnalysis',
  file=DESCRIPTOR,
  index=5,
  options=None,
  serialized_start=897,
  serialized_end=978,
  methods=[
  _descriptor.MethodDescriptor(
    name='streamAnalysis',
    full_name='TwitterStreamAnalysis.streamAnalysis',
    index=0,
    containing_service=None,
    input_type=_TWITTERINPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWITTERSTREAMANALYSIS)

DESCRIPTOR.services_by_name['TwitterStreamAnalysis'] = _TWITTERSTREAMANALYSIS


_TRAINDATA = _descriptor.ServiceDescriptor(
  name='TrainData',
  full_name='TrainData',
  file=DESCRIPTOR,
  index=6,
  options=None,
  serialized_start=980,
  serialized_end=1033,
  methods=[
  _descriptor.MethodDescriptor(
    name='train',
    full_name='TrainData.train',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINDATA)

DESCRIPTOR.services_by_name['TrainData'] = _TRAINDATA

# @@protoc_insertion_point(module_scope)
