# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/model/sentiment_analysis_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/model/sentiment_analysis_rpc.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n+services/model/sentiment_analysis_rpc.proto\"\x1d\n\x0cInputMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x1e\n\rOutputMessage\x12\r\n\x05value\x18\x01 \x01(\t\";\n\x13TwitterInputMessage\x12\x11\n\tlanguages\x18\x01 \x01(\t\x12\x11\n\tsentences\x18\x02 \x01(\t\"%\n\x14TwitterOutputMessage\x12\r\n\x05value\x18\x01 \x01(\t26\n\x0bShowMessage\x12\'\n\x04show\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32T\n\x1aSentimentIntensityAnalysis\x12\x36\n\x13intensivityAnalysis\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32N\n\x18SentimentComplexAnalysis\x12\x32\n\x0f\x63omplexAnalysis\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32O\n\x14\x43ustomCorpusAnalysis\x12\x37\n\x14\x63ustomCorpusAnalysis\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32L\n\x0fTwitterAnalysis\x12\x39\n\x0ftwitterAnalysis\x12\x14.TwitterInputMessage\x1a\x0e.OutputMessage\"\x00\x32\x35\n\tTrainData\x12(\n\x05train\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x62\x06proto3')
)




_INPUTMESSAGE = _descriptor.Descriptor(
  name='InputMessage',
  full_name='InputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='InputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=76,
)


_OUTPUTMESSAGE = _descriptor.Descriptor(
  name='OutputMessage',
  full_name='OutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='OutputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=108,
)


_TWITTERINPUTMESSAGE = _descriptor.Descriptor(
  name='TwitterInputMessage',
  full_name='TwitterInputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='languages', full_name='TwitterInputMessage.languages', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentences', full_name='TwitterInputMessage.sentences', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=169,
)


_TWITTEROUTPUTMESSAGE = _descriptor.Descriptor(
  name='TwitterOutputMessage',
  full_name='TwitterOutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='TwitterOutputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['InputMessage'] = _INPUTMESSAGE
DESCRIPTOR.message_types_by_name['OutputMessage'] = _OUTPUTMESSAGE
DESCRIPTOR.message_types_by_name['TwitterInputMessage'] = _TWITTERINPUTMESSAGE
DESCRIPTOR.message_types_by_name['TwitterOutputMessage'] = _TWITTEROUTPUTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputMessage = _reflection.GeneratedProtocolMessageType('InputMessage', (_message.Message,), dict(
  DESCRIPTOR = _INPUTMESSAGE,
  __module__ = 'services.model.sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:InputMessage)
  ))
_sym_db.RegisterMessage(InputMessage)

OutputMessage = _reflection.GeneratedProtocolMessageType('OutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTMESSAGE,
  __module__ = 'services.model.sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:OutputMessage)
  ))
_sym_db.RegisterMessage(OutputMessage)

TwitterInputMessage = _reflection.GeneratedProtocolMessageType('TwitterInputMessage', (_message.Message,), dict(
  DESCRIPTOR = _TWITTERINPUTMESSAGE,
  __module__ = 'services.model.sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:TwitterInputMessage)
  ))
_sym_db.RegisterMessage(TwitterInputMessage)

TwitterOutputMessage = _reflection.GeneratedProtocolMessageType('TwitterOutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _TWITTEROUTPUTMESSAGE,
  __module__ = 'services.model.sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:TwitterOutputMessage)
  ))
_sym_db.RegisterMessage(TwitterOutputMessage)



_SHOWMESSAGE = _descriptor.ServiceDescriptor(
  name='ShowMessage',
  full_name='ShowMessage',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=210,
  serialized_end=264,
  methods=[
  _descriptor.MethodDescriptor(
    name='show',
    full_name='ShowMessage.show',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOWMESSAGE)

DESCRIPTOR.services_by_name['ShowMessage'] = _SHOWMESSAGE


_SENTIMENTINTENSITYANALYSIS = _descriptor.ServiceDescriptor(
  name='SentimentIntensityAnalysis',
  full_name='SentimentIntensityAnalysis',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=266,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='intensivityAnalysis',
    full_name='SentimentIntensityAnalysis.intensivityAnalysis',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTIMENTINTENSITYANALYSIS)

DESCRIPTOR.services_by_name['SentimentIntensityAnalysis'] = _SENTIMENTINTENSITYANALYSIS


_SENTIMENTCOMPLEXANALYSIS = _descriptor.ServiceDescriptor(
  name='SentimentComplexAnalysis',
  full_name='SentimentComplexAnalysis',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=352,
  serialized_end=430,
  methods=[
  _descriptor.MethodDescriptor(
    name='complexAnalysis',
    full_name='SentimentComplexAnalysis.complexAnalysis',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTIMENTCOMPLEXANALYSIS)

DESCRIPTOR.services_by_name['SentimentComplexAnalysis'] = _SENTIMENTCOMPLEXANALYSIS


_CUSTOMCORPUSANALYSIS = _descriptor.ServiceDescriptor(
  name='CustomCorpusAnalysis',
  full_name='CustomCorpusAnalysis',
  file=DESCRIPTOR,
  index=3,
  options=None,
  serialized_start=432,
  serialized_end=511,
  methods=[
  _descriptor.MethodDescriptor(
    name='customCorpusAnalysis',
    full_name='CustomCorpusAnalysis.customCorpusAnalysis',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMCORPUSANALYSIS)

DESCRIPTOR.services_by_name['CustomCorpusAnalysis'] = _CUSTOMCORPUSANALYSIS


_TWITTERANALYSIS = _descriptor.ServiceDescriptor(
  name='TwitterAnalysis',
  full_name='TwitterAnalysis',
  file=DESCRIPTOR,
  index=4,
  options=None,
  serialized_start=513,
  serialized_end=589,
  methods=[
  _descriptor.MethodDescriptor(
    name='twitterAnalysis',
    full_name='TwitterAnalysis.twitterAnalysis',
    index=0,
    containing_service=None,
    input_type=_TWITTERINPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWITTERANALYSIS)

DESCRIPTOR.services_by_name['TwitterAnalysis'] = _TWITTERANALYSIS


_TRAINDATA = _descriptor.ServiceDescriptor(
  name='TrainData',
  full_name='TrainData',
  file=DESCRIPTOR,
  index=5,
  options=None,
  serialized_start=591,
  serialized_end=644,
  methods=[
  _descriptor.MethodDescriptor(
    name='train',
    full_name='TrainData.train',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINDATA)

DESCRIPTOR.services_by_name['TrainData'] = _TRAINDATA

# @@protoc_insertion_point(module_scope)
